declare const styles: {
  readonly formBuilder: string
  readonly label: string
  readonly container: string
  readonly smColSpan1: string
  readonly smColSpan2: string
  readonly smColSpan3: string
  readonly smColSpan4: string
  readonly smColSpan5: string
  readonly smColSpan6: string
  readonly smColSpan7: string
  readonly smColSpan8: string
  readonly smColSpan9: string
  readonly smColSpan10: string
  readonly smColSpan11: string
  readonly smColSpan12: string
  readonly mdColSpan1: string
  readonly mdColSpan2: string
  readonly mdColSpan3: string
  readonly mdColSpan4: string
  readonly mdColSpan5: string
  readonly mdColSpan6: string
  readonly mdColSpan7: string
  readonly mdColSpan8: string
  readonly mdColSpan9: string
  readonly mdColSpan10: string
  readonly mdColSpan11: string
  readonly mdColSpan12: string
  readonly lgColSpan1: string
  readonly lgColSpan2: string
  readonly lgColSpan3: string
  readonly lgColSpan4: string
  readonly lgColSpan5: string
  readonly lgColSpan6: string
  readonly lgColSpan7: string
  readonly lgColSpan8: string
  readonly lgColSpan9: string
  readonly lgColSpan10: string
  readonly lgColSpan11: string
  readonly lgColSpan12: string
}

export default styles
