declare const styles: {
  readonly formBuilder: string
  readonly label: string
  readonly container: string
  readonly colSpan1: string
  readonly colSpan2: string
  readonly colSpan3: string
  readonly colSpan4: string
  readonly colSpan5: string
  readonly colSpan6: string
  readonly colSpan7: string
  readonly colSpan8: string
  readonly colSpan9: string
  readonly colSpan10: string
  readonly colSpan11: string
  readonly colSpan12: string
  readonly mdColSpan1: string
  readonly mdColSpan2: string
  readonly mdColSpan3: string
  readonly mdColSpan4: string
  readonly mdColSpan5: string
  readonly mdColSpan6: string
  readonly mdColSpan7: string
  readonly mdColSpan8: string
  readonly mdColSpan9: string
  readonly mdColSpan10: string
  readonly mdColSpan11: string
  readonly mdColSpan12: string
  readonly lgColSpan1: string
  readonly lgColSpan2: string
  readonly lgColSpan3: string
  readonly lgColSpan4: string
  readonly lgColSpan5: string
  readonly lgColSpan6: string
  readonly lgColSpan7: string
  readonly lgColSpan8: string
  readonly lgColSpan9: string
  readonly lgColSpan10: string
  readonly lgColSpan11: string
  readonly lgColSpan12: string
}

export default styles
